default-money: 1000

command:
  general:
    not-found-player: "%ERROR% %0のデータは存在しません。"
    negative-amount: "%ERROR% マイナスの値は設定できません。"
    less-than-zero: "%ERROR% 所持金が0以下になるため、この操作はできません。"
  money:
    success: "%INFO% あなたの所持金は%0円です。"
  set:
    success: "%SUCCESS% %0の所持金を%1円に設定しました。"
    usage: "/money set <プレイヤー名> <金額>"
  show:
    success: "%INFO% %0の所持金は%1円です。"
    usage: "/money show <プレイヤー名>"
  plus:
    success: "%SUCCESS% %0の所持金を%1円増やしました。"
    usage: "/money plus <プレイヤー名> <金額>"
  minus:
    success: "%SUCCESS% %0の所持金を%1円減らしました。"
    usage: "/money minus <プレイヤー名> <金額>"

# sqlite or mysql
db-type: sqlite
sqlite:
  file: mooney-core.sqlite3
mysql:
  address: localhost
  port: 3306
  database: example
  user: root
  password: password
