default-money: 1000

command:
  general:
    not-found-player: "%ERROR% %0のデータは存在しません。"
    negative-amount: "%ERROR% マイナスの値は設定できません。"
  set-money:
    success: "%SUCCESS% %0の所持金を%1円に設定しました。"
    usage: "/money set <プレイヤー名> <金額>"
  show-money:
    success: "%SUCCESS% %0の所持金は%1円です。"


# sqlite or mysql
db-type: sqlite
sqlite:
  file: mooney-core.sqlite3
mysql:
  address: localhost
  port: 3306
  database: example
  user: root
  password: password
